services:
  - type: web
    name: jobrite
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn jobrite_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SUPABASE_URL
        value: https://wmefqsnpmhbpuqybhusu.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtZWZxc25wbWhicHVxeWJodXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjYyMTQsImV4cCI6MjA3MDc0MjIxNH0.V5H-LLnIvVYQ0WvY5ftwWq5ZnFKOkPNt4czcaiuH4WM
      - key: SUPABASE_SERVICE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtZWZxc25wbWhicHVxeWJodXN1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTE2NjIxNCwiZXhwIjoyMDcwNzQyMjE0fQ.M48dyDv81BMl73Df5BCopEEfStt_fOrfAMdBFRGcJBo
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
      - key: DEFAULT_FROM_EMAIL
        value: JobRite Team <noreply@jobrite.com>